src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Model\Localizable;
use App\Repository\ArtistRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/** * @SuppressWarnings(PHPMD.ExcessiveClassComplexity) */
#[ORM\Entity(repositoryClass: ArtistRepository::class)]
class Artist implements Localizable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djInfos'])]
    #[Assert\NotBlank(groups: ['djInfos'])]
    private string $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djInfos'])]
    #[Assert\NotBlank(groups: ['djInfos'])]
    private string $lastname;

    #[ORM\Column(type: 'date')]
    #[Assert\NotBlank(groups: ['djInfos'])]
    private DateTime $birthdate;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djInfos'])]
    #[Assert\NotBlank(groups: ['djInfos'])]
    private string $phone;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private string $email;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djInfos'])]
    #[Assert\NotBlank(groups: ['djInfos'])]
    private string $address;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djProfile'])]
    #[Assert\NotBlank(groups: ['djProfile'])]
    private string $artistName;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(max: 255, groups: ['djProfile'])]
    #[Assert\NotBlank(groups: ['djProfile'])]
    private string $equipment;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Length(max: 255, groups: ['djProfile'])]
    private ?string $message = null;

    #[ORM\ManyToMany(targetEntity: MusicalStyle::class, inversedBy: 'artists', cascade: ['persist'])]
    #[Assert\Count(
        min: 1,
        groups: ['djProfile'],
        minMessage: 'Merci de choisir au moins {{ limit }} genre musical'
    )]
    private Collection $musicalStyles;

    #[ORM\OneToMany(mappedBy: 'artist', targetEntity: Reservation::class)]
    private Collection $reservations;

    #[ORM\OneToOne(inversedBy: 'artist', targetEntity: User::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: 'float', nullable: true)]
    private ?float $longitude;

    #[ORM\Column(type: 'float', nullable: true)]
    private ?float $latitude;

    #[ORM\OneToOne(inversedBy: 'artist', targetEntity: Document::class, cascade: ['persist', 'remove'])]
    private ?Document $documents = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Url]
    private ?string $instagram;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Url]
    private ?string $soundCloud;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Url]
    private ?string $facebook;

    #[ORM\OneToMany(mappedBy: 'artist', targetEntity: Unavailability::class, orphanRemoval: true)]
    private Collection $unavailabilities;


    public function __construct()
    {
        $this->musicalStyles = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->unavailabilities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;
        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getBirthdate(): ?\DateTime
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTime $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getArtistName(): ?string
    {
        return $this->artistName;
    }

    public function setArtistName(string $artistName): self
    {
        $this->artistName = $artistName;

        return $this;
    }

    public function getEquipment(): ?string
    {
        return $this->equipment;
    }

    public function setEquipment(string $equipment): self
    {
        $this->equipment = $equipment;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return Collection<int, MusicalStyle>
     */
    public function getMusicalStyles(): Collection
    {
        return $this->musicalStyles;
    }

    public function addMusicalStyle(MusicalStyle $musicalStyle): self
    {
        if (!$this->musicalStyles->contains($musicalStyle)) {
            $this->musicalStyles[] = $musicalStyle;
        }

        return $this;
    }

    public function removeMusicalStyle(MusicalStyle $musicalStyle): self
    {
        $this->musicalStyles->removeElement($musicalStyle);

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setArtist($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getArtist() === $this) {
                $reservation->setArtist(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getDocuments(): ?Document
    {
        return $this->documents;
    }

    public function setDocuments(?Document $documents): self
    {
        $this->documents = $documents;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getSoundCloud(): ?string
    {
        return $this->soundCloud;
    }

    public function setSoundCloud(?string $soundCloud): self
    {
        $this->soundCloud = $soundCloud;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    /**
     * @return Collection<int, Unavailability>
     */
    public function getUnavailabilities(): Collection
    {
        return $this->unavailabilities;
    }

    public function addUnavailability(Unavailability $unavailability): self
    {
        if (!$this->unavailabilities->contains($unavailability)) {
            $this->unavailabilities[] = $unavailability;
            $unavailability->setArtist($this);
        }

        return $this;
    }

    public function removeUnavailability(Unavailability $unavailability): self
    {
        if ($this->unavailabilities->removeElement($unavailability)) {
            // set the owning side to null (unless already changed)
            if ($unavailability->getArtist() === $this) {
                $unavailability->setArtist(null);
            }
        }

        return $this;
    }
}

templates/dj_dashboard/_cards_dj.html.twig
<div class="col-lg-6 my-3">
	<div class="card-dj shadow border border-dark rounded-3 w-100">
		<div class="d-lg-flex h-100 rounded-3 {% if reservation.artist is defined and reservation.artist == app.user.artist %} dj-my-events {% elseif reservation.artist is not null and reservation.artist != app.user.artist %} dj-other-events {% else %} dj-new-events {% endif %}">
			<div class="d-flex flex-column justify-content-around align-items-start px-5 rounded-3 col-lg-6">
				<h1 class="h4 mb-0 mb-lg-4 text-light">{{ reservation.company }}</h1>
				<div class="d-none d-lg-flex flex-column resa-header">
					<p class="card-text text-light d-flex fs-5 mb-2">
					<i class="bi bi-calendar me-2"></i>
						{{ reservation.dateStart|date("d/m/Y") }}</p>
					<p class="card-text text-light fs-5">
						<i class="bi bi-cursor-fill me-1"></i>
						{{ reservation.distance }}
						km</p>
				</div>
			</div>
			<div class="d-flex flex-column justify-content-between col-lg-6">
				<div class="my-3 flex-grow-1 justify-content-around flex-column d-flex px-2">
					<p class="card-text m-0">
						<i class="bi bi-geo-alt-fill me-1"></i>
						{{ reservation.address|u.truncate(50, '...', false) }}</p>
					<p class="card-text m-0">
						<i class="bi bi-telephone-fill me-1"></i>
						{{ reservation.phone }}
					</p>
					<class="card-text">
					{% if reservation.price is not null %}
						<i class="bi bi-currency-exchange me-1"></i>
						{{ reservation.price }}
						€
					{% else %}
					Tarif non précisé
					{% endif %}
					</p>
				</div>
				<div class="w-100 pe-lg-3 pb-lg-3 pb-2">
						<div class="w-100 px-2 mb-2">
							<a href="{{ path('dashboard_dj_show', {'id': reservation.id}) }}" class="btn btn-outline-primary w-100">En savoir plus</a>
						</div>
					{% if reservation.artist == app.user.artist %}
						{{ include('dj_dashboard/reservation/_cancel_reservation.html.twig') }}
					{% elseif reservation.artist is null and reservation.status != 'Rejected' %}
						{% include 'dj_dashboard/reservation/_accept_reservation.html.twig' %}
					{% else %}
						<p class=" py-2 border-2 border-dark mx-2 border-top mb-0">Cet évènement est déjà réservé par un autre DJ.</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

templates/dj_dashboard/dj_dashboard_base.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} | Espace DJ
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('djDashboard') }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('sidebar') }}
{% endblock %}

{% block navbar %}
	{% include 'components/_dj_topbar.html.twig' %}
{% endblock %}

{% block message %}
{% endblock %}

{% block body %}
	<div class="d-flex">
		{% include 'components/_dj_sidebar.html.twig' %}
		<div class="w-100">
			{% include 'components/_flash_message.html.twig' %}
			{% block content %}
			{% endblock %}
		</div>
	</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/dj_dashboard/index.html.twig
{% extends 'dj_dashboard/dj_dashboard_base.html.twig' %}

{% block title %}
	{{ parent() }}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
{% endblock %}

{% block content %}
	<main class="mx-auto">
		<div class="container d-flex flex-column mb-5">
			{% if is_granted('ROLE_USER') and not is_granted('ROLE_DJ') %}
				<div class="d-flex flex-column justify-content-center align-items-center">
					<h1 class="mt-5">Votre candidature est en attente de confirmation.</h1>
					<p class="fs-4 text-muted">Afin qu'aoyos puisse valider votre candidature, merci de compléter
						<a href="{{ path('dashboard_dj_documents') }}">votre dossier</a>.</p>
				</div>
			{% else %}
				<section class="reservations-dj">
					<h1 class="mt-5 mb-2">
						Nouveaux évènements
					</h1>
					<div class="row">
						{% for reservation in newReservations %}
							{% include 'dj_dashboard/_cards_dj.html.twig' %}

						{% else %}
							<p class="ms-lg-4">Aucun nouvel évènement trouvé.</p>
						{% endfor %}
						<div class="d-flex justify-content-center">
							<a class="btn w-25 btn-outline-dark" href="{{ path('dashboard_dj_reservations') }}">Voir plus</a>
						</div>
					</div>
					<h1 class="mt-3 mb-2">
						Mes évènements
					</h1>
					<div class="row">
						{% for reservation in reservations %}
							{% include 'dj_dashboard/_cards_dj.html.twig' %}
						{% else %}
							<p class="m-4">Vous n'avez pas encore d'évènement.</p>
						{% endfor %}
					</div>
					<div class="d-flex justify-content-center">
						<a class="btn w-25 btn-outline-dark" href="{{ path('dashboard_dj_my_events', {'filter': 'a-venir'}) }}">Voir plus</a>
					</div>
				{% endif %}
				</section>
			</div>
		</main>
	{% endblock %}

templates/dj_dashboard/my_events.html.twig
{% extends 'dj_dashboard/dj_dashboard_base.html.twig' %}

{% block title %}
	{{ parent() }}
	- Mes évènements
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
{% endblock %}

{% block content %}
	<main class="container d-flex flex-column mt-5">

		<section class="reservations-dj">
			<h1 class="mt-3 mb-2 ms-3">
				Mes évènements
				{% if filter == constant('App\\Repository\\ReservationRepository::PAST_EVENTS') %}
					passés
				{% elseif filter == constant('App\\Repository\\ReservationRepository::FUTURE_EVENTS') %}
					à venir
				{% endif %}
			</h1>
			<div class="table-responsive">
				<table class="table table-hover my-4">
					<thead>
						<tr>
							<th>Société</th>
							<th>Début</th>
							<th>Fin</th>
							<th>Tarif</th>
							{% if filter == constant('App\\Repository\\ReservationRepository::PAST_EVENTS') %}
								<th class="text-center">Facture</th>
							{% endif %}
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for reservation in reservations %}
							<tr>
								<td class="align-middle">{{ reservation.company }}</td>
								<td class="align-middle">{{ reservation.dateStart ? reservation.dateStart|date('d-m-Y H:i') : '' }}</td>
								<td class="align-middle">{{ reservation.dateEnd ? reservation.dateEnd|date('d-m-Y H:i') : '' }}</td>
								<td class="align-middle">{{ reservation.price ? reservation.price ~ '€' : 'Non précisé' }}</td>
								{% if filter == constant('App\\Repository\\ReservationRepository::PAST_EVENTS') %}
									<td class="align-middle text-center">
										<i class="bi bi-{{ reservation.bill ? 'check2-square' : 'file-excel' }}"></i>
									</td>
								{% endif %}
								<td class="align-middle text-end">
									<a class="btn btn-outline-dark btn-sm text-nowrap px-3 me-2" href="{{ path('dashboard_dj_show', {'id': reservation.id}) }}">
										<i class="bi bi-eye"></i>
										Détail</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="7">Aucun évènement trouvé</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</section>
	</main>
{% endblock %}

templates/dj_dashboard/notification_email_new_bill.html.twig
{% extends "layout_email.html.twig" %}

{% block title %}
	{{ parent() }}
	- Nouvelle facture
{% endblock %}

{% block body %}
	<h1 class="fs-4">Bonjour aoyos</h1>
	<h2 class="fs-5 my-3">Une nouvelle facture de
		{{ user.artist.fullname }}
	</h2>
	<p class="m-3">Pour l'évènement
		{{ reservation.company }}</p>
	<p class="m-3">Du
		{{ reservation.dateStart |date('d-m-Y H:i') }}
		au
		{{ reservation.dateEnd |date('d-m-Y H:i') }}</p>

{% endblock %}

templates/dj_dashboard/notification_email_reservation_canceled.html.twig
{% extends "layout_email.html.twig" %}

{% block title %}
	{{ parent() }}
	- Presation annulée
{% endblock %}

{% block body %}
	<h1 class="fs-4">Bonjour aoyos</h1>
	<h2 class="fs-5 my-3">{{ artist.artistName }} s'est retiré de l'évènement {{ reservation.company }}</h2>
    <h3 class="mt-3">Pour contacter l'artiste : </h3>
    <p class="m-3">{{ artist.firstname }} {{ artist.lastname }}</p>
    <p class="m-3">{{ artist.phone }}</p>
    <p class="m-3">{{ artist.email }}</p>
{% endblock %}

templates/dj_dashboard/notification_email_reservation_validated.html.twig
{% extends "layout_email.html.twig" %}

{% block title %}
	{{ parent() }}
	- Attribution d'évènement
{% endblock %}

{% block body %}
	<h1 class="fs-4">Bonjour aoyos</h1>
	<h2 class="fs-5 my-3">{{ reservation.artist.artistName }} a accepté l'évènement de {{ reservation.company }}</h2>
    <h3 class="mt-3">Détail de l'évènement : </h3>
    <p class="m-3">Formule: {{ reservation.formula }}</p>
	<p class="m-3">Lieu: {{ reservation.address }}</p>
	<p class="m-3">Du {{ reservation.dateStart |date('d-m-Y H:i') }} au {{ reservation.dateEnd |date('d-m-Y H:i') }}</p>
    <p class="m-3">Participants: {{ reservation.attendees }}</p>
{% endblock %}